[[redirects]]
  from = "/"
  to = "/login-clean.html"
  status = 200

[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*.mov"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"