name = "zantara-proxy-bff"
main = "src/index.js"
compatibility_date = "2024-04-02"

[vars]
# Base Cloud Run URL (no trailing slash)
ZANTARA_BASE_URL = "https://zantara-v520-production-1064094238013.europe-west1.run.app"
# Allowed origin for browser requests
ALLOW_ORIGIN = "https://zantara.balizero.com"

# Set the secret at deploy time (never commit):
# wrangler secret put ZANTARA_API_KEY
